# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-26 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170717_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='publicationDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication date'),
        ),
    ]
