# Generated by Django 5.2.3 on 2026-06-09 03:40

import djangocms_text.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_latestnewspluginmodel_cmsplugin_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='content',
            field=djangocms_text.fields.HTMLField(help_text='Insert news content here.', verbose_name='Content'),
        ),
    ]
