# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannedperson',
            name='lastName',
            field=models.CharField(max_length=30, verbose_name='Last name'),
        ),
    ]
