# Generated by Django 2.1.7 on 2019-03-23 03:46

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('banlist', '0002_auto_20181114_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannedperson',
            name='photo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_person_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Photo'),
        ),
    ]
