# Generated by Django 2.2.11 on 2020-06-16 02:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import merch.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0033_auto_20200124_1349'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Give a descriptive name for this item.', max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Provide a full item description for customers.', null=True, verbose_name='Item Description')),
                ('defaultPrice', models.FloatField(default=0, help_text='This price may be overridden by a particular item variant.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Default price')),
                ('salesTaxRate', models.FloatField(default=merch.models.get_defaultSalesTaxRate, help_text="The sales tax percentage rate to be applied to this item (e.g. enter '10' to apply 10 percent sales tax).", validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sales tax rate')),
                ('buyerPaysSalesTax', models.BooleanField(default=merch.models.get_defaultBuyerPaysSalesTax, help_text='If unchecked, then the buyer will not be charged sales tax directly, but the amount of tax collected by the business will be reported.', verbose_name='Buyer pays sales tax (added to total price)')),
                ('disabled', models.BooleanField(default=False, help_text='If checked, then this item will not be available for purchase, regardless of current inventory.', verbose_name='Item disabled')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('photo', filer.fields.image.FilerImageField(blank=True, help_text='Individual item variants may have their own photos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_photo', to=settings.FILER_IMAGE_MODEL, verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Merchandise item',
                'verbose_name_plural': 'Merchandise items',
            },
        ),
        migrations.CreateModel(
            name='MerchItemVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='The SKU for this item variant.', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z\\-_0-9]+$')], verbose_name='SKU')),
                ('name', models.CharField(blank=True, help_text='Give a unique name for this variant (e.g. "Size Medium")', max_length=100, null=True, verbose_name='Name')),
                ('price', models.FloatField(blank=True, help_text='If specified, then price supercedes the item default price.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('originalQuantity', models.PositiveIntegerField(help_text='For inventory purposes, enter an initial quantity here', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Original Quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_variant', to='merch.MerchItem', verbose_name='Item')),
                ('photo', filer.fields.image.FilerImageField(blank=True, help_text='A photo specific to this variant, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemvariant_photo', to=settings.FILER_IMAGE_MODEL, verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Item variant',
                'verbose_name_plural': 'Item variants',
            },
        ),
        migrations.CreateModel(
            name='MerchOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UN', 'Not yet submitted'), ('SU', 'Submitted'), ('AP', 'Approved for fulfillment'), ('F', 'Fulfilled'), ('C', 'Cancelled')], default='UN', help_text='Use the order status to keep track of submission, processing, shipment (if applicable), and fulfillment.', max_length=2, verbose_name='Order status')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
                ('invoice', models.OneToOneField(blank=True, help_text='All submitted merchandise orders must be associated with an invoice.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Invoice')),
            ],
            options={
                'verbose_name': 'Merchandise order',
                'verbose_name_plural': 'Merchandise orders',
            },
        ),
        migrations.CreateModel(
            name='MerchQuantityAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Change in inventory quantity')),
                ('submissionDate', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_adjustments', to='merch.MerchItemVariant')),
            ],
        ),
        migrations.CreateModel(
            name='MerchOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('invoiceItem', models.OneToOneField(blank=True, help_text='All submitted merchandise order must be associated with an invoice.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.InvoiceItem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='merch.MerchItemVariant', verbose_name='Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='merch.MerchOrder')),
            ],
            options={
                'verbose_name': 'Merchandise order item',
                'verbose_name_plural': 'Merchandise order items',
            },
        ),
        migrations.AddConstraint(
            model_name='merchorder',
            constraint=models.CheckConstraint(check=models.Q(('status', 'UN'), ('invoice__isnull', False), _connector='OR'), name='submitted_has_invoice'),
        ),
        migrations.AlterUniqueTogether(
            name='merchitemvariant',
            unique_together={('item', 'name')},
        ),
    ]
