# Generated by Django 2.2.13 on 2020-08-04 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0006_doorregisterguestsearchpluginmodel'),
        ('cms', '0022_auto_20180620_1551'),
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Give a descriptive name for this category.', max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Merchandise category',
                'verbose_name_plural': 'Merchandise category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DoorRegisterMerchPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='merch_doorregistermerchpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, default='Merchandise', max_length=250, verbose_name='Custom list title')),
                ('separateVariants', models.BooleanField(default=False, verbose_name='Display item variants as separate items')),
                ('displaySoldOut', models.BooleanField(default=False, verbose_name='Display items and variants that are sold out')),
                ('requireFullRegistration', models.BooleanField(blank=True, default=True, help_text='If checked, then the user will be sent to the second page of the registration process to provide name and email. Particular payment methods may also require the full registration process.', verbose_name='Require full registration')),
                ('template', models.CharField(blank=True, max_length=250, null=True, verbose_name='Plugin template')),
                ('cssClasses', models.CharField(blank=True, help_text='Classes are applied to surrounding &lt;div&gt;', max_length=250, null=True, verbose_name='Custom CSS classes')),
                ('categories', models.ManyToManyField(blank=True, help_text='Leave blank for no restriction', to='merch.MerchItemCategory', verbose_name='Limit to merchandise categories')),
                ('paymentMethods', models.ManyToManyField(blank=True, help_text='If you would like separate buttons for individual payment methods, then select them here.  If left blank, a single button will be shown and no payment method will be specified.', to='door.DoorRegisterPaymentMethod', verbose_name='Payment Methods')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='merchitem',
            name='category',
            field=models.ForeignKey(help_text='Used on product pages to determine what items to list.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='merch.MerchItemCategory'),
        ),
    ]
