# Generated by Django 2.2.13 on 2020-08-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_auto_20200803_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchitemvariant',
            name='soldOut',
            field=models.BooleanField(default=False, verbose_name='Sold out'),
        ),
    ]
