# Generated by Django 2.2.17 on 2021-01-28 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0003_merchitemvariant_soldout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchorder',
            name='invoice',
            field=models.OneToOneField(blank=True, help_text='All submitted merchandise orders must be associated with an invoice.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchOrder', to='core.Invoice'),
        ),
        migrations.AlterField(
            model_name='merchorderitem',
            name='invoiceItem',
            field=models.OneToOneField(blank=True, help_text='All submitted merchandise orders must be associated with an invoice.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.InvoiceItem'),
        ),
    ]
