# Generated by Django 3.1.6 on 2021-02-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0003_doorregistermerchpluginmodel_autofulfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchorder',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Additional data'),
        ),
    ]
