# Generated by Django 3.1.6 on 2021-02-20 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('merch', '0005_auto_20210220_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermerchpluginmodel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='merch_registermerchpluginmodel', serialize=False, to='cms.cmsplugin'),
        ),
    ]
