# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-14 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20181109_1631'),
        ('vouchers', '0004_customergroupvoucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicEventCategoryVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicEventCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PublicEventCategory', verbose_name='Public Event Category')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.Voucher', verbose_name='Voucher')),
            ],
            options={
                'verbose_name': 'Public event category-specific voucher restriction',
                'verbose_name_plural': 'public event Category-specific voucher restrictions'
            },
        ),
        migrations.CreateModel(
            name='SeriesCategoryVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriesCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SeriesCategory', verbose_name='Series Category')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.Voucher', verbose_name='Voucher')),
            ],
            options={
                'verbose_name': 'Series category-specific voucher restriction',
                'verbose_name_plural': 'Series category-specific voucher restrictions'
            },
        ),
        migrations.CreateModel(
            name='SessionVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EventSession', verbose_name='Event Session')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.Voucher', verbose_name='Voucher')),
            ],
            options={
                'verbose_name': 'Session-specific voucher restriction',
                'verbose_name_plural': 'Session-specific voucher restrictions',
            },
        ),
    ]
