# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-25 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_publiceventcategoryvoucher_seriescategoryvoucher_sessionvoucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vouchers.VoucherCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='voucheruse',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Registration', verbose_name='Registration'),
        ),
    ]
