# Generated by Django 2.2.6 on 2019-10-28 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0006_auto_20190322_2346'),
        ('vouchers', '0006_auto_20191025_1826'),
    ]

    operations = [
    ]
