# Generated by Django 2.2.6 on 2020-01-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0007_merge_20191028_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='doorOnly',
            field=models.BooleanField(default=False, verbose_name='At-the-door Registrations Only'),
        ),
    ]
