# Generated by Django 2.2.6 on 2020-01-14 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0008_voucher_dooronly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucherId',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z\\-_0-9]+$')], verbose_name='Voucher Code'),
        ),
    ]
