# Generated by Django 2.2.17 on 2021-01-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0010_auto_20200210_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucheruse',
            name='applied',
            field=models.BooleanField(
                null=True, verbose_name='Use finalized'
            ),
        ),
        migrations.DeleteModel(
            name='TemporaryVoucherUse',
        ),
    ]
