# Generated by Django 3.1.6 on 2021-02-12 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20210205_2231'),
        ('vouchers', '0012_existing_vouchers_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucheruse',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.invoice', verbose_name='Invoice'),
        ),
    ]
