# Generated by Django 3.1.6 on 2021-02-12 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0014_voucheruse_registration_to_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucheruse',
            name='registration',
        ),
        migrations.AlterField(
            model_name='voucheruse',
            name='invoice',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='core.invoice', verbose_name='Invoice'),
        ),
    ]
