# Generated by Django 3.1.6 on 2021-02-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0015_voucheruse_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='beforeTax',
            field=models.BooleanField(default=True, help_text='Voucher codes that are used as discounts or promotions are usually subtracted from the total price before any applicable sales tax is calculated, while gift certificates are subtracted from the after-tax total price.', verbose_name='Voucher applied before tax'),
        ),
        migrations.AddField(
            model_name='voucheruse',
            name='beforeTax',
            field=models.BooleanField(default=True, verbose_name='Voucher applied before tax'),
        ),
    ]
