# Generated by Django 2.1.7 on 2019-03-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestlist', '0002_guestlistname_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlist',
            name='includeRegistrants',
            field=models.BooleanField(blank=True, default=True, verbose_name='Include event registrants'),
        ),
        migrations.AlterField(
            model_name='guestlist',
            name='includeStaff',
            field=models.BooleanField(blank=True, default=True, verbose_name='Include all scheduled event staff'),
        ),
    ]
