# Generated by Django 2.2.6 on 2020-02-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestlist', '0003_auto_20190322_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestlistname',
            options={'ordering': ('guestList', 'lastName', 'firstName'), 'permissions': (('view_guestlist', 'Can view guest lists'), ('checkin_guests', 'Can check in guests using the JSON check-in view (used by door plugins)')), 'verbose_name': 'Manually-added guest', 'verbose_name_plural': 'Manually added guests'},
        ),
    ]
