# Generated by Django 3.1.6 on 2022-01-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestlist', '0004_auto_20200211_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestlistname',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Email (optional)'),
        ),
    ]
