# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-11 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0007_customergroupdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcombo',
            name='firstXRegistered',
            field=models.PositiveSmallIntegerField(blank=True, help_text='For this discount to apply, all components must be satisfied by events that have fewer than this many individuals registered (including registrations in progress). Only one discount per category can be applied, so if you define tiered discounts in the same category, only the best available discount will be used.', null=True, verbose_name='Only for first __ registrants'),
        ),
        migrations.AlterField(
            model_name='discountcombo',
            name='daysInAdvanceRequired',
            field=models.PositiveIntegerField(blank=True, help_text='For this discount to apply, all components must be satisfied by events that begin this many days in the future (measured from midnight of the date of registration). Leave blank for no restriction.', null=True, verbose_name='Must register __ days in advance'),
        ),
    ]
