# Generated by Django 2.1.7 on 2019-03-23 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0008_auto_20180811_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcombo',
            name='category',
            field=models.ForeignKey(help_text='One discount can be applied per category, and the order in which discounts are applied depends on the order parameter of the categories.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.DiscountCategory', verbose_name='Discount category'),
        ),
        migrations.AlterField(
            model_name='discountcombocomponent',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DanceTypeLevel', verbose_name='Dance type/level'),
        ),
    ]
