# Generated by Django 2.2.17 on 2021-01-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0010_merge_20191028_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdiscount',
            name='applied',
            field=models.BooleanField(null=True, verbose_name='Use finalized'),
        ),
        migrations.DeleteModel(
            name='TemporaryRegistrationDiscount',
        ),
    ]
