# Generated by Django 3.1.6 on 2021-02-28 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0012_existing_discounts_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcombo',
            name='firstXRegistered',
            field=models.SmallIntegerField(blank=True, help_text='For this discount to apply, all components must be satisfied by events that have fewer than this many individuals registered (including registrations in progress). Only one discount per category can be applied, so if you define tiered discounts in the same category, only the best available discount will be used.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Only for first __ registrants'),
        ),
    ]
