# Generated by Django 3.1.6 on 2021-03-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0013_auto_20210227_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcombo',
            name='customerMatchRequired',
            field=models.BooleanField(default=False, help_text='If checked, then this discount will only be applied once the name associated with each registration on the invoice can be verified, and only if the subset of registrations with the same name can qualify for the discount.', verbose_name='Registration names must match invoice'),
        ),
    ]
