# Generated by Django 3.1.6 on 2022-03-10 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20210324_0009'),
        ('discounts', '0014_discountcombo_customermatchrequired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingtiergroup',
            name='pricingTier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pricingtier', verbose_name='Pricing tier'),
        ),
    ]
