# Generated by Django 3.2.16 on 2023-05-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0015_auto_20220310_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcombo',
            name='availableAtDoor',
            field=models.BooleanField(default=True, help_text='Uncheck this to prevent individuals who register at the door from receiving this discount', verbose_name='Available for at-the-door registrations'),
        ),
        migrations.AddField(
            model_name='discountcombo',
            name='availableOnline',
            field=models.BooleanField(default=True, help_text='Uncheck this to prevent individuals who register in advance from receiving this discount', verbose_name='Available for online pre-registrations'),
        ),
    ]
