# Generated by Django 5.2.3 on 2025-10-11 02:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0016_auto_20230505_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcombo',
            name='voucherId',
            field=models.CharField(blank=True, help_text='If specified, then this discount will only be applied if the voucher code has been passed', max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z\\-_0-9]*$')], verbose_name='Voucher code to access discount'),
        ),
    ]
