# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squarepaymentrecord',
            name='locationId',
            field=models.CharField(max_length=100, verbose_name='Square Location ID'),
        ),
        migrations.AlterField(
            model_name='squarepaymentrecord',
            name='transactionId',
            field=models.CharField(max_length=100, unique=True, verbose_name='Square Transaction ID'),
        ),
    ]
