# Generated by Django 3.1.6 on 2022-01-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0002_auto_20190109_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squarepaymentrecord',
            old_name='transactionId',
            new_name='orderId'
        ),
        migrations.AlterField(
            model_name='squarepaymentrecord',
            name='orderId',
            field=models.CharField(db_column='transactionId', max_length=100, null=True, unique=True, verbose_name='Square Order ID'),
        ),
        migrations.AddField(
            model_name='squarepaymentrecord',
            name='paymentId',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Square Payment ID'),
        ),
        migrations.AddConstraint(
            model_name='squarepaymentrecord',
            constraint=models.CheckConstraint(check=models.Q(('orderId__isnull', False), ('paymentId__isnull', False), _connector='OR'), name='order_or_payment_specified'),
        ),
    ]
