# Generated by Django 3.1.6 on 2022-01-29 01:12

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('square', '0003_auto_20220128_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squarecheckoutformmodel',
            name='successPage',
            field=cms.models.fields.PageField(blank=True, help_text='When the user returns to the site after a successful transaction, send them to this page.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='successPageForSquare', to='cms.page', verbose_name='Success Page'),
        ),
    ]
