# Generated by Django 3.2.16 on 2023-03-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0004_auto_20220128_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='squarepaymentrecord',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Additional data'),
        ),
    ]
