# Generated by Django 5.0.9 on 2025-01-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0006_alter_squarecheckoutformmodel_cmsplugin_ptr'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='squarepaymentrecord',
            name='order_or_payment_specified',
        ),
        migrations.AlterField(
            model_name='squarepaymentrecord',
            name='paymentId',
            field=models.CharField(max_length=100, unique=True, verbose_name='Square Payment ID'),
        ),
    ]
