# Generated by Django 5.0.9 on 2025-01-10 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0007_remove_squarepaymentrecord_order_or_payment_specified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquarePayoutRecord',
            fields=[
                ('payoutId', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Square Payout ID')),
                ('locationId', models.CharField(editable=False, max_length=100, verbose_name='Square Location ID')),
                ('creationDate', models.DateTimeField(verbose_name='Payout creation date')),
                ('modifiedDate', models.DateTimeField(verbose_name='Payout modified date')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Additional data')),
            ],
            options={
                'verbose_name': 'Square payout record',
                'verbose_name_plural': 'Payout records',
            },
        ),
        migrations.CreateModel(
            name='SquarePayoutEntry',
            fields=[
                ('entryId', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Square Payout Entry ID')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Additional data')),
                ('paymentRecord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='square.squarepaymentrecord')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='square.squarepayoutrecord')),
            ],
            options={
                'verbose_name': 'Square payout entry',
                'verbose_name_plural': 'Payout entries',
            },
        ),
    ]
