# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 17:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_auto_20170720_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalHereRecord',
            fields=[
                ('paymentrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.PaymentRecord')),
                ('paypalInvoiceId', models.CharField(max_length=50, unique=True, verbose_name='Paypal Invoice ID')),
                ('paymentType', models.CharField(blank=True, max_length=50, null=True, verbose_name='Transaction Type')),
                ('txId', models.CharField(blank=True, max_length=50, null=True, verbose_name='Merchant Tax ID')),
                ('total', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount paid')),
                ('payerEmail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Payer email')),
            ],
            options={
                'verbose_name_plural': 'Paypal Here payment records',
                'permissions': (('process_paypal_here_payments', 'Can process point-of-sale payments using Paypal Here'),),
                'verbose_name': 'Paypal Here payment record',
            },
            bases=('core.paymentrecord',),
        ),
    ]
