# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-26 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_auto_20170717_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='submissionDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Submission date'),
        ),
        migrations.AlterField(
            model_name='revenueitem',
            name='submissionDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Submission date'),
        ),
    ]
