# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 23:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170809_2342'),
        ('financial', '0005_auto_20170726_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationRentalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentalRate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rental Rate')),
                ('applyRateRule', models.CharField(choices=[('H', 'Per hour'), ('D', 'Per day of scheduled events'), ('W', 'Per week'), ('M', 'Per month'), ('N', 'Do not generate expense items for this location')], default='H', help_text='When ExpenseItems are created for rentals, the given rate will be applied for this unit of time to compute the total cost of rental.', max_length=1, verbose_name='Apply this rate')),
                ('weekStarts', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Rental week starts on')),
                ('monthStarts', models.PositiveSmallIntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th'), (11, '11th'), (12, '12th'), (13, '13th'), (14, '14th'), (15, '15th'), (16, '16th'), (17, '17th'), (18, '18th'), (19, '19th'), (20, '20th'), (21, '21st'), (22, '22nd'), (23, '23rd'), (24, '24th'), (25, '25th'), (26, '26th'), (27, '27th'), (28, '28th')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Rental month starts on')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rentalinfo', to='core.Location', verbose_name='Location')),
            ],
            options={
                'verbose_name_plural': "Locations' rental information",
                'verbose_name': 'Location rental information',
            },
        ),
        migrations.CreateModel(
            name='RoomRentalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentalRate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rental Rate')),
                ('applyRateRule', models.CharField(choices=[('H', 'Per hour'), ('D', 'Per day of scheduled events'), ('W', 'Per week'), ('M', 'Per month'), ('N', 'Do not generate expense items for this location')], default='H', help_text='When ExpenseItems are created for rentals, the given rate will be applied for this unit of time to compute the total cost of rental.', max_length=1, verbose_name='Apply this rate')),
                ('weekStarts', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Rental week starts on')),
                ('monthStarts', models.PositiveSmallIntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th'), (11, '11th'), (12, '12th'), (13, '13th'), (14, '14th'), (15, '15th'), (16, '16th'), (17, '17th'), (18, '18th'), (19, '19th'), (20, '20th'), (21, '21st'), (22, '22nd'), (23, '23rd'), (24, '24th'), (25, '25th'), (26, '26th'), (27, '27th'), (28, '28th')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Rental month starts on')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rentalinfo', to='core.Room', verbose_name='Room')),
            ],
            options={
                'verbose_name_plural': "Rooms' rental information",
                'verbose_name': 'Room rental information',
            },
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='periodEnd',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expense period end'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='periodStart',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expense period start'),
        ),
    ]
