# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 21:21
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_auto_20170811_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseitem',
            name='eventstaffmember',
        ),
        migrations.RemoveField(
            model_name='expenseitem',
            name='eventvenue',
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.ExpenseCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='event',
            field=models.ForeignKey(blank=True, help_text='If this item is associated with an Event, enter it here.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='expenseRule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.RepeatedExpenseRule', verbose_name='Expense generation rule'),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='payToUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payToUser', to=settings.AUTH_USER_MODEL, verbose_name='Pay to user'),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='submissionUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expensessubmittedby', to=settings.AUTH_USER_MODEL, verbose_name='Submission user'),
        ),
        migrations.AlterField(
            model_name='repeatedexpenserule',
            name='advanceDays',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Generate expenses up to __ days in advance'),
        ),
        migrations.AlterField(
            model_name='repeatedexpenserule',
            name='applyRateRule',
            field=models.CharField(choices=[('H', 'Per hour'), ('D', 'Per day of scheduled events'), ('W', 'Per week'), ('M', 'Per month'), ('N', 'Do not generate expense items for this location')], default='H', max_length=1, verbose_name='Apply this rate'),
        ),
        migrations.AlterField(
            model_name='repeatedexpenserule',
            name='dayStarts',
            field=models.PositiveSmallIntegerField(choices=[(0, '12:00 AM'), (1, '1:00 AM'), (2, '2:00 AM'), (3, '3:00 AM'), (4, '4:00 AM'), (5, '5:00 AM'), (6, '6:00 AM'), (7, '7:00 AM'), (8, '8:00 AM'), (9, '9:00 AM'), (10, '10:00 AM'), (11, '11:00 AM'), (12, '12:00 PM'), (13, '1:00 PM'), (14, '2:00 PM'), (15, '3:00 PM'), (16, '4:00 PM'), (17, '5:00 PM'), (18, '6:00 PM'), (19, '7:00 PM'), (20, '8:00 PM'), (21, '9:00 PM'), (22, '10:00 PM'), (23, '11:00 PM')], default=0, help_text='If you run events after midnight, avoids creation of duplicate expense items', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Day starts at'),
        ),
        migrations.AlterField(
            model_name='repeatedexpenserule',
            name='priorDays',
            field=models.PositiveSmallIntegerField(blank=True, default=180, help_text='Leave blank for no limit.', null=True, verbose_name='Generate expenses up to __ days in the past'),
        ),
        migrations.AlterField(
            model_name='repeatedexpenserule',
            name='rentalRate',
            field=models.FloatField(blank=True, help_text='In default currency', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Expense Rate'),
        ),
        migrations.AlterField(
            model_name='revenueitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.RevenueCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='revenueitem',
            name='submissionUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenuessubmittedby', to=settings.AUTH_USER_MODEL, verbose_name='Submission user'),
        ),
        migrations.AlterField(
            model_name='staffmemberwageinfo',
            name='category',
            field=models.ForeignKey(blank=True, help_text='If left blank, then this expense rule will be used for all categories.  If a category-specific rate is specified, then that will be used instead.  If nothing is specified for an instructor, then the default hourly rate for each category will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.EventStaffCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='staffmemberwageinfo',
            name='staffMember',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenserules', to='core.StaffMember', verbose_name='Staff member'),
        ),
    ]
