# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_auto_20170823_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenueitem',
            name='buyerPaysSalesTax',
            field=models.BooleanField(default=False, verbose_name='Buyer pays sales tax'),
        ),
    ]
