# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-09 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_auto_20171204_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmemberwageinfo',
            name='category',
            field=models.ForeignKey(blank=True, help_text='If left blank, then this expense rule will be used for all categories.  If a category-specific rate is specified, then that will be used instead.  If nothing is specified for a staff member, then the default hourly rate for each category will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.EventStaffCategory', verbose_name='Category'),
        ),
    ]
