# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-19 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20181109_1631'),
        ('financial', '0010_auto_20181109_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDefaultWage',
            fields=[
                ('repeatedexpenserule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financial.RepeatedExpenseRule')),
                ('category', models.OneToOneField(help_text='If left blank, then this expense rule will be used for all categories.  If a category-specific rate is specified, then that will be used instead.  If nothing is specified for a staff member, then the default hourly rate for each category will be used.', on_delete=django.db.models.deletion.CASCADE, related_name='defaultwage', to='core.EventStaffCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Default staff wage',
                'verbose_name_plural': 'Default staff wages',
                'ordering': ('category__name',),
                'manager_inheritance_from_future': True,
            },
            bases=('financial.repeatedexpenserule',),
        ),
    ]
