# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-20 01:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0012_auto_20181216_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseitem',
            name='payToLocation',
        ),
        migrations.RemoveField(
            model_name='expenseitem',
            name='payToName',
        ),
        migrations.RemoveField(
            model_name='expenseitem',
            name='payToUser',
        ),
        migrations.RemoveField(
            model_name='genericrepeatedexpense',
            name='payToLocation',
        ),
        migrations.RemoveField(
            model_name='genericrepeatedexpense',
            name='payToName',
        ),
        migrations.RemoveField(
            model_name='genericrepeatedexpense',
            name='payToUser',
        ),
        migrations.RemoveField(
            model_name='revenueitem',
            name='receivedFromName',
        ),
    ]
