# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0014_auto_20190322_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repeatedexpenserule',
            options={'permissions': (('can_generate_repeated_expenses', 'Able to generate rule-based repeated expenses using the admin view'),), 'verbose_name': 'Repeated expense rule', 'verbose_name_plural': 'Repeated expense rules'},
        ),
    ]
