# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-16 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0016_auto_20190409_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Additional data'),
        ),
        migrations.AddField(
            model_name='revenueitem',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Additional data'),
        ),
    ]
