# Generated by Django 2.1.7 on 2019-04-12 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0016_auto_20190409_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='attachment',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_attachment', to='filer.File', verbose_name='Attach File (optional)'),
        ),
        migrations.AlterField(
            model_name='revenueitem',
            name='attachment',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_attachment', to='filer.File', verbose_name='Attach File (optional)'),
        ),
        migrations.AlterField(
            model_name='revenueitem',
            name='currentlyHeldBy',
            field=models.ForeignKey(blank=True, help_text='If cash has not yet been deposited, this indicates who to contact in order to collect the cash for deposit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenuesheldby', to=settings.AUTH_USER_MODEL, verbose_name='Cash currently in possession of'),
        ),
        migrations.AlterField(
            model_name='revenueitem',
            name='event',
            field=models.ForeignKey(blank=True, help_text='If this item is associated with an Event, enter it here.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='revenueitem',
            name='invoiceItem',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.InvoiceItem', verbose_name='Associated invoice item'),
        ),
    ]
