# Generated by Django 2.1.7 on 2019-08-23 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0018_auto_20190412_1528'),
        ('financial', '0017_auto_20190816_1755'),
    ]

    operations = [
    ]
