# Generated by Django 2.2.17 on 2021-01-28 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0020_auto_20200127_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenueitem',
            name='invoiceItem',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.InvoiceItem', verbose_name='Associated invoice item'),
        ),
    ]
