# Generated by Django 3.1.6 on 2022-01-14 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('financial', '0021_auto_20210127_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensePurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.expenseitem', verbose_name='Expense item purpose')),
            ],
        ),
    ]
