# Generated by Django 3.1.6 on 2022-01-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0022_expensepurpose'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='expenseitem',
            constraint=models.UniqueConstraint(fields=('expenseRule', 'payTo', 'periodStart', 'periodEnd', 'category'), name='unique_payment_per_rule_recipient_time_and_category'),
        ),
        migrations.AddConstraint(
            model_name='transactionparty',
            constraint=models.CheckConstraint(check=models.Q(('name__isnull', False), ('user__isnull', False), ('staffMember__isnull', False), ('location__isnull', False), _connector='OR'), name='must_specify_party'),
        ),
    ]
