# Generated by Django 5.2.3 on 2026-02-22 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0024_alter_repeatedexpenserule_polymorphic_ctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='total',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total amount'),
        ),
    ]
