# Generated by Django 5.2.3 on 2026-03-18 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_event_registrationopendate'),
        ('financial', '0025_alter_expenseitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensepurpose',
            name='occurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_purposes', to='core.eventoccurrence', verbose_name='Event occurrence'),
        ),
    ]
