# Generated by Django 5.2.3 on 2026-06-09 03:40

import djangocms_text.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_alter_faqcategorypluginmodel_cmsplugin_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=djangocms_text.fields.HTMLField(help_text='Answer the question.', verbose_name='Answer'),
        ),
    ]
