from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.core.validators import MinValueValidator
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

from filer.fields.file import FilerFileField
from filer.models import Folder

from danceschool.core.models import Event, InvoiceItem
from danceschool.core.constants import getConstant

from ..managers import RevenueItemManager
from .parties import TransactionParty


class RevenueCategory(models.Model):
    '''
    These are the different available categories of payment
    '''

    name = models.CharField(
        _('Name'), max_length=50, unique=True,
        help_text=_('Different types of revenue fall under different categories.')
    )
    defaultAmount = models.FloatField(
        _('Default amount'),
        help_text=_('This is the default amount of revenue for items in this category.'),
        null=True, blank=True, validators=[MinValueValidator(0)]
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Revenue category')
        verbose_name_plural = _('Revenue categories')


class RevenueItem(models.Model):
    '''
    All revenue-producing transactions (e.g. class payments, other payments)
    should have an associated RevenueItem
    '''

    # Custom model manager to add net annotation.
    objects = RevenueItemManager()

    submissionUser = models.ForeignKey(
        User, null=True, blank=True, related_name='revenuessubmittedby',
        verbose_name=_('Submission user'), on_delete=models.SET_NULL,)
    submissionDate = models.DateTimeField(_('Submission date'), auto_now_add=True)

    category = models.ForeignKey(RevenueCategory, verbose_name=_('Category'), null=True, on_delete=models.SET_NULL,)
    description = models.CharField(_('Description'), max_length=200, null=True, blank=True)
    total = models.FloatField(
        _('Total'),
        help_text=_(
            'The total revenue received, net of any discounts or voucher uses.  ' +
            'This is what we actually receive.'
        ),
        validators=[MinValueValidator(0)]
    )
    grossTotal = models.FloatField(
        _('Gross Total'),
        help_text=_(
            'The gross total billed before the application of any discounts, ' +
            'or the use of any vouchers.'
        ),
        validators=[MinValueValidator(0)]
    )
    adjustments = models.FloatField(
        _('Adjustments'),
        help_text=_(
            'Record any ex-post adjustments to the amount (e.g. refunds) in ' +
            'this field.  A positive amount increases the netRevenue, a ' +
            'negative amount reduces the netRevenue.'
        ),
        default=0
    )
    fees = models.FloatField(
        _('Fees'),
        help_text=_(
            'The sum of any transaction fees (e.g. Paypal fees) that were ' +
            'paid <strong>by us</strong>, and should therefore be subtracted ' +
            'from net revenue.'
        ),
        default=0
    )
    taxes = models.FloatField(_('Taxes'), default=0)
    buyerPaysSalesTax = models.BooleanField(_('Buyer pays sales tax'), default=False)

    paymentMethod = models.CharField(_('Payment method'), max_length=50, null=True, blank=True)
    invoiceNumber = models.CharField(
        _('Invoice Number'),
        help_text=_(
            'For Paypal payments, this will be the txn_id.  For cash payments, ' +
            'this will be automatically generated by the submission form.  ' +
            'More than one revenue item may have the same invoice number, ' +
            'because multiple events are paid for in one Paypal transaction.'
        ),
        null=True, blank=True, max_length=80
    )

    comments = models.TextField(_('Comments/Notes'), null=True, blank=True)
    attachment = FilerFileField(
        verbose_name=_('Attach File (optional)'), null=True, blank=True,
        related_name='revenue_attachment', on_delete=models.SET_NULL,
    )

    # With the invoice system in the core app, Revenue Items need only link with Invoice Items
    invoiceItem = models.OneToOneField(
        InvoiceItem, null=True, blank=True, verbose_name=_('Associated invoice item'),
        on_delete=models.CASCADE,
    )

    event = models.ForeignKey(
        Event, null=True, blank=True, verbose_name=_('Event'),
        help_text=_('If this item is associated with an Event, enter it here.'),
        on_delete=models.SET_NULL,
    )

    # A revenue item is associated with a transaction party, which can be a User, a StaffMember,
    # a Location, or just a name of the party.  If the revenue item is associated with a Registration,
    # then it is associated with a Customer, and it does not require a separate value for receivedFrom.
    receivedFrom = models.ForeignKey(
        TransactionParty, null=True, blank=True, verbose_name=_('Pay to'), on_delete=models.SET_NULL,
    )

    currentlyHeldBy = models.ForeignKey(
        User, null=True, blank=True, verbose_name=_('Cash currently in possession of'),
        help_text=_(
            'If cash has not yet been deposited, this indicates who to contact in ' +
            'order to collect the cash for deposit.'
        ),
        related_name='revenuesheldby', on_delete=models.SET_NULL,
    )
    received = models.BooleanField(
        _('Received'),
        help_text=_(
            'Check to indicate that payment has been received. ' +
            'Non-received payments are considered pending.'
        ),
        default=False
    )
    receivedDate = models.DateTimeField(_('Date received'), null=True, blank=True)

    # This field is used to aggregate expenses over time (e.g. by month).
    # The value of this field is auto-updated using pre-save methods. If
    # there is a registration or an event associated with this expense,
    # then the value is taken from that.  Otherwise, the submission date
    # is used.
    accrualDate = models.DateTimeField(_('Accrual date'))

    data = models.JSONField(_('Additional data'), default=dict, blank=True)

    @property
    def relatedItems(self):
        '''
        If this item is associated with a registration, then return all other items associated with
        the same registration.
        '''
        if getattr(getattr(self,'registration', None), 'pk', None):
            return self.registration.revenueitem_set.exclude(pk=self.pk)
    relatedItems.fget.short_description = _('Related items')

    @property
    def netRevenue(self):
        ''' Use the database annotation where possible. '''
        net = getattr(self, 'net', None)
        if net is None:
            net = (self.total or 0) + self.adjustments - self.fees
            if not self.buyerPaysSalesTax:
                net -= self.taxes
        return net
    netRevenue.fget.short_description = _('Net revenue')

    @property
    def allocationByOccurrence(self):
        '''
        Provide a default allocation across event occurrences that is solely
        based on the duration of all occurrences of the event.
        '''
        if not getattr(getattr(self, 'event', None), 'pk', None):
            return {}

        # Uses prefetch cache if eventoccurrence_set was prefetched
        occurrences = list(self.event.eventoccurrence_set.all())

        # Compute duration in Python instead of via DB annotation
        for occ in occurrences:
            occ._dur = (occ.endTime - occ.startTime).total_seconds()

        sum_dur = sum(o._dur for o in occurrences)
        if not sum_dur:
            return {}

        return {
            (x.id, x.event_id): {  # use x.event_id (cached FK) not x.event.id
                'allocation': x._dur / sum_dur,
                'total_duration': sum_dur,
                'duration': x._dur,
            }
            for x in occurrences
        }

    def getAllocationForOccurrences(self, **kwargs):
        occurrences = kwargs.get('occurrences', None)
        if not occurrences:
            return 0
        allocation_by_occurrence = self.allocationByOccurrence
        return sum([
            allocation_by_occurrence.get(
                (o.id, o.event.id), {}
            ).get('allocation', 0) for o in occurrences
        ])

    def getAllocation(self, events=None, occurrences=None):
        if occurrences:
            return self.getAllocationForOccurrences(occurrences=occurrences)
        elif events and self.event not in events:
            0
        else:
            return 1

    def save(self, *args, **kwargs):
        '''
        This custom save method ensures that a revenue item is not attributed to multiple categories.
        It also ensures that the series and event properties are always associated with any
        type of revenue of that series or event.
        '''

        # Set the received date if the payment was just marked received
        if not hasattr(self, '__received'):
            if self.received and not self.receivedDate:
                self.receivedDate = timezone.now()
        else:
            if self.received and not self.receivedDate and not self.__receivedDate:
                self.receivedDate = timezone.now()

        # Set the accrual date. For series/event registrations, the accrualDate
        # is set based on the first occurrence of the event (or the first
        # occurrence associated with the registration for drop-ins.
        if not self.accrualDate:
            if self.invoiceItem and getattr(self.invoiceItem, 'eventRegistration', None):
                er = self.invoiceItem.eventRegistration
                self.accrualDate = (
                    getattr(er.occurrences.order_by('startTime').first(), 'startTime', None) or
                    er.event.startTime
                )
            elif self.event:
                self.accrualDate = self.event.startTime

            if not self.accrualDate and self.invoiceItem:
                self.accrualDate = self.invoiceItem.invoice.creationDate
            elif self.receivedDate:
                self.accrualDate = self.receivedDate
            elif self.submissionDate:
                self.accrualDate = self.submissionDate
            else:
                self.submissionDate = timezone.now()
                self.accrualDate = self.submissionDate

        # Now, set the registration property and check that this item is not attributed
        # to multiple categories.
        if self.invoiceItem and getattr(self.invoiceItem,'eventRegistration', None):
            self.event = self.invoiceItem.eventRegistration.event
        elif self.invoiceItem and getattr(self.invoiceItem,'eventRegistration', None):
            self.event = self.invoiceItem.eventRegistration.event

        # If no grossTotal is reported, use the net total.  If no net total is reported, use the grossTotal
        if self.grossTotal is None and self.total:
            self.grossTotal = self.total
        if self.total is None and self.grossTotal:
            self.total = self.grossTotal

        super().save(*args, **kwargs)
        self.__received = self.received
        self.__receivedDate = self.receivedDate

        # If a file is attached, ensure that it is not public, and that it is
        # saved in the 'Expense Receipts' folder
        if self.attachment:
            try:
                self.attachment.folder = Folder.objects.get(name=_('Revenue Receipts'))
            except ObjectDoesNotExist:
                pass
            self.attachment.is_public = False
            self.attachment.save()

    def __str__(self):
        if self.accrualDate:
            return '%s %s: %s = %s%s' % (
                getattr(self.category, 'name', str(_('Revenue'))),
                self.accrualDate.strftime('%B %Y'),
                self.description, getConstant('general__currencySymbol'),
                self.total
            )
        else:
            return '%s: %s = %s%s' % (
                getattr(self.category, 'name', str(_('Expense'))),
                self.description,
                getConstant('general__currencySymbol'), self.total
            )

    def __init__(self, *args, **kwargs):
        '''
        Permit easy checking to determine if the object
        already exists and has changed on saving
        '''
        super().__init__(*args, **kwargs)
        self.__received = self.received
        self.__receivedDate = self.receivedDate

    class Meta:
        ordering = ['-accrualDate', ]
        verbose_name = _('Revenue item')
        verbose_name_plural = _('Revenue items')

        permissions = (
            ('mark_revenues_received', _('Mark revenues as received at the time of submission')),
            ('export_financial_data', _('Export detailed financial transaction information to CSV')),
            ('view_finances_bymonth', _('View school finances month-by-month')),
            ('view_finances_bydate', _('View school finances day-by-day')),
            ('view_finances_byevent', _('View school finances by Event')),
            ('view_finances_detail', _('View school finances as detailed statement')),
        )
