# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-20 21:46
from __future__ import unicode_literals

import colorful.fields
import danceschool.core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_dancetypelevel_requiresaudition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancetypelevel',
            name='displayColor',
            field=colorful.fields.RGBColorField(default=danceschool.core.models.get_defaultClassColor, help_text='Choose a color for the calendar display.', verbose_name='Display Color'),
        ),
        migrations.AlterField(
            model_name='publiceventcategory',
            name='displayColor',
            field=colorful.fields.RGBColorField(default='#0000FF', help_text='Choose a color for the calendar display.'),
        ),
    ]
