# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170717_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='html_content',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Emails are sent as plain text by default.  To send an HTML email instead, enter your desired content in this field.', null=True, verbose_name='HTML Rich Text content'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='richTextChoice',
            field=models.CharField(choices=[('plain', 'Plain text email'), ('HTML', 'HTML rich text email')], default='plain', max_length=5, verbose_name='Send this email as'),
        ),
    ]
