# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 23:33
from __future__ import unicode_literals

import danceschool.core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170720_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Give this room a name.', max_length=80, unique=True, verbose_name='Name')),
                ('rentalRate', models.FloatField(blank=True, help_text='When ExpenseItems are created for renting this room, this rental rate will be used to calculate the total cost of rental.  If no value is specified, then the default for the Location will be used.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hourly Rental Rate (optional)')),
                ('defaultCapacity', models.PositiveIntegerField(blank=True, default=danceschool.core.models.get_defaultEventCapacity, help_text='If set, this will be used to determine capacity for class series in this room.', null=True, verbose_name='Default Venue Capacity')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='By default, only room names are listed publicly.  However, you may insert any descriptive information that you would like about this room here.', null=True, verbose_name='Description')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location', verbose_name='Location')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
                'ordering': ('location__name', 'name'),
                'verbose_name': 'Room',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Room', verbose_name='Room'),
        ),
    ]
