# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170803_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text='Give this room a name.', max_length=80, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set([('location', 'name')]),
        ),
    ]
