# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170809_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventstaffcategory',
            name='defaultRate',
        ),
        migrations.AlterUniqueTogether(
            name='eventstaffmember',
            unique_together=set([('staffMember', 'event', 'category', 'replacedStaffMember')]),
        ),
    ]
