# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-23 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20180810_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-startTime',), 'verbose_name': 'Series/Event', 'verbose_name_plural': 'All Series/Events'},
        ),
    ]
