# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180823_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlistpluginmodel',
            name='eventCategories',
            field=models.ManyToManyField(blank=True, help_text='Leave blank for no restriction', to='core.PublicEventCategory', verbose_name='Limit to public event categories'),
        ),
        migrations.AddField(
            model_name='eventlistpluginmodel',
            name='levels',
            field=models.ManyToManyField(blank=True, help_text='Leave blank for no restriction', to='core.DanceTypeLevel', verbose_name='Limit to type and levels'),
        ),
        migrations.AddField(
            model_name='eventlistpluginmodel',
            name='limitNumber',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Leave blank for no restriction', null=True, verbose_name='Limit number'),
        ),
        migrations.AddField(
            model_name='eventlistpluginmodel',
            name='seriesCategories',
            field=models.ManyToManyField(blank=True, help_text='Leave blank for no restriction', to='core.SeriesCategory', verbose_name='Limit to series categories'),
        ),
        migrations.AddField(
            model_name='eventlistpluginmodel',
            name='sortOrder',
            field=models.CharField(choices=[('A', 'Ascending'), ('D', 'Descending')], default='A', help_text='This may be overridden by the particular template in use', max_length=1, verbose_name='Sort by start time'),
        ),
        migrations.RemoveField(
            model_name='eventlistpluginmodel',
            name='location',
        ),
        migrations.AddField(
            model_name='eventlistpluginmodel',
            name='location',
            field=models.ManyToManyField(blank=True, help_text='Leave blank for no restriction', to='core.Location', verbose_name='Limit to locations'),
        ),
    ]
