# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20180919_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='When choosing staff members, the individuals available to staff will be limited based on the categories chosen here.', to='core.EventStaffCategory', verbose_name='Included in staff categories'),
        ),
    ]
