# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-25 22:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_event_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Staff photo'),
        ),
    ]
