# Generated by Django 2.1.7 on 2019-08-23 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190403_2336'),
        ('core', '0026_event_data'),
    ]

    operations = [
    ]
