# Generated by Django 2.2.6 on 2020-01-07 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_merge_20190822_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ('-dateTime',), 'permissions': (('view_registration_summary', 'Can access the series-level registration summary view'), ('checkin_customers', 'Can check-in customers using the summary view'), ('accept_door_payments', 'Can process door payments in the registration system'), ('register_dropins', 'Can register students for drop-ins.'), ('override_register_closed', 'Can register students for series/events that are closed for registration by the public'), ('override_register_soldout', 'Can register students for series/events that are officially sold out'), ('override_register_dropins', 'Can register students for drop-ins even if the series does not allow drop-in registration.'), ('ajax_registration', 'Can register using the Ajax registration view (needed for the door register)')), 'verbose_name': 'Registration', 'verbose_name_plural': 'Registrations'},
        ),
    ]
