# Generated by Django 2.2.6 on 2020-01-20 18:23

import danceschool.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_datamigrate_20200116_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='checkedIn',
        ),
        migrations.AlterField(
            model_name='event',
            name='closeAfterDays',
            field=models.FloatField(blank=True, default=danceschool.core.models.get_closeAfterDays, help_text='Enter positive values to close after first event occurrence, and negative values to close before first event occurrence.  Leave blank to keep registration open until the event has ended entirely.', null=True, verbose_name='Registration closes days from first occurrence'),
        ),
    ]
