# Generated by Django 2.2.6 on 2020-01-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200120_1323'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='temporaryeventregistration',
            unique_together=set(),
        ),
    ]
