# Generated by Django 2.2.17 on 2021-02-02 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_fix_reg_invoice_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='expirationDate',
        ),
    ]
