# Generated by Django 2.2.17 on 2021-02-02 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_fix_reg_invoice_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='final',
            field=models.BooleanField(null=False, default=False, verbose_name='Registration has been finalized'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='invoiceItem',
            field=models.OneToOneField(null=False, on_delete=django.db.models.deletion.CASCADE, related_name='eventRegistration', to='core.InvoiceItem', verbose_name='Invoice item'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='invoice',
            field=models.OneToOneField(null=False, on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='core.Invoice', verbose_name='Invoice'),
        ),
        migrations.RemoveField(
            model_name='registration',
            name='expirationDate',
        ),
    ]
