# Generated by Django 3.1.6 on 2021-02-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20210205_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Additional data'),
        ),
    ]
