# Generated by Django 3.1.6 on 2021-02-20 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20210220_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashpaymentrecord',
            name='refundAmount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount refunded'),
        ),
    ]
