# Generated by Django 3.1.6 on 2021-02-26 01:03

import danceschool.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_cashpaymentrecord_refundamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdescription',
            name='template',
            field=models.CharField(default=danceschool.core.models.get_defaultSeriesPageTemplate, max_length=250, verbose_name='Template for automatically-generated class series page'),
        ),
        migrations.AddField(
            model_name='publicevent',
            name='template',
            field=models.CharField(default=danceschool.core.models.get_defaultPublicEventPageTemplate, max_length=250, verbose_name='Template for automatically-generated event page'),
        ),
    ]
