# Generated by Django 3.1.6 on 2021-02-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20210225_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='student',
            field=models.BooleanField(default=False, verbose_name='Eligible for student discount'),
        ),
    ]
