# Generated by Django 3.1.6 on 2021-02-26 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_set_eventregistration_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='student',
        ),
    ]
