# Generated by Django 3.1.6 on 2021-03-23 23:13

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_event_partnerrequired'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventoccurrence',
            constraint=models.CheckConstraint(check=models.Q(endTime__gte=django.db.models.expressions.F('startTime')), name='core_eventoccurrence_correct_endTime'),
        ),
    ]
