# Generated by Django 3.1.6 on 2021-03-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20210323_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendarEvent',
            field=models.BooleanField(null=True, verbose_name='Visible on public calendars'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('D', 'Registration disabled'), ('O', 'Registration enabled'), ('K', 'Registration held closed (override default behavior)'), ('H', 'Registration held open (override default)'), ('L', 'Registration open, but hidden from registration page (link required to register)'), ('C', 'Hidden from registration page, registration closed, potentially visible on calendar.'), ('X', 'Event hidden, registration closed, always hidden from calendar')], help_text='Set the registration status and visibility status of this event.', max_length=1, verbose_name='Registration status'),
        ),
    ]
