# Generated by Django 3.1.6 on 2021-03-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_set_calendarevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='calendarEvent',
            field=models.BooleanField(default=True, verbose_name='Visible on public calendars'),
        ),
    ]
