# Generated by Django 3.2.12 on 2022-08-18 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20210324_0009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventDJ',
        ),
        migrations.DeleteModel(
            name='SeriesStaffMember',
        ),
        migrations.DeleteModel(
            name='SeriesTeacher',
        ),
        migrations.AlterModelOptions(
            name='substituteteacher',
            options={'permissions': (('report_substitute_teaching', 'Can access the substitute reporting form'),), 'verbose_name': 'Substitute staff member', 'verbose_name_plural': 'Substitute staff members'},
        ),
    ]
