# Generated by Django 3.2.16 on 2023-06-09 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20221106_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-modifiedDate',), 'permissions': (('view_all_invoices', 'Can view invoices without passing the validation string.'), ('send_invoices', 'Can send invoices to students requesting payment'), ('process_refunds', 'Can refund customers for registrations and other invoice payments.'), ('export_invoice_data', 'Can export data related to invoices and their items')), 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
    ]
