# Generated by Django 5.2.3 on 2026-03-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_event_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registrationOpenDate',
            field=models.DateTimeField(blank=True, help_text='If set, registration will automatically open at this date and time. Only applies when registration status is set to "Registration enabled" or "Link only". Leave blank to open registration immediately when the event is saved with one of those statuses.', null=True, verbose_name='Registration opens at'),
        ),
    ]
