# Generated by Django 5.2.3 on 2026-06-09 03:40

import djangocms_text.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_public_register_plugins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdescription',
            name='description',
            field=djangocms_text.fields.HTMLField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_content',
            field=djangocms_text.fields.HTMLField(blank=True, help_text='Emails are sent as plain text by default.  To send an HTML email instead, enter your desired content in this field.', null=True, verbose_name='HTML rich text content'),
        ),
        migrations.AlterField(
            model_name='location',
            name='directions',
            field=djangocms_text.fields.HTMLField(blank=True, help_text='Insert any detailed directions that you would like here.  Use HTML to include videos, formatting, etc.', null=True, verbose_name='Directions'),
        ),
        migrations.AlterField(
            model_name='publicevent',
            name='descriptionField',
            field=djangocms_text.fields.HTMLField(blank=True, help_text='Describe the event for the event page.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=djangocms_text.fields.HTMLField(blank=True, help_text='By default, only room names are listed publicly.  However, you may insert any descriptive information that you would like about this room here.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='bio',
            field=djangocms_text.fields.HTMLField(blank=True, help_text="Insert the instructor's bio here.  Use HTML to include videos, formatting, etc.", null=True, verbose_name='Bio text'),
        ),
    ]
