# Generated by Django 3.2.16 on 2022-11-21 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20221106_1552'),
        ('private_lessons', '0002_instructoravailabilityslot_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructoravailabilityslot',
            options={'ordering': ('-startTime', 'instructor__staffMember__lastName', 'instructor__staffMember__firstName'), 'permissions': (('edit_own_availability', "Can edit one's own private lesson availability."), ('edit_others_availability', "Can edit other instructors' private lesson availability.")), 'verbose_name': 'Private lesson availability slot', 'verbose_name_plural': 'Private lesson availability slots'},
        ),
        migrations.AlterField(
            model_name='instructoravailabilityslot',
            name='eventRegistration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privateLessonSlots', to='core.eventregistration', verbose_name='event registration'),
        ),
        migrations.AlterField(
            model_name='instructorprivatelessondetails',
            name='defaultPricingTier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pricingtier', verbose_name='Default Pricing Tier'),
        ),
        migrations.AlterField(
            model_name='instructorprivatelessondetails',
            name='instructor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.staffmember'),
        ),
        migrations.AlterField(
            model_name='privatelessonevent',
            name='pricingTier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pricingtier', verbose_name='Pricing Tier'),
        ),
    ]
