# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-13 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0002_auto_20170717_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementitem',
            name='concurrentRule',
            field=models.CharField(choices=[('P', 'Must have previously taken'), ('1', 'May register/begin with one class remaining'), ('1', 'May register/begin with two classes remaining'), ('A', 'Concurrent registration allowed'), ('R', 'Concurrent registration required')], default='P', max_length=1, verbose_name='Concurrency Rule'),
        ),
    ]
