# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-25 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0003_auto_20170813_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequirement',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Role must be specified only for requirements for which roles are enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DanceRole', verbose_name='Dance role'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='applicableClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ClassDescription', verbose_name='Applies to class'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='applicableLevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DanceTypeLevel', verbose_name='Applies to dance type/level'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='applicableRole',
            field=models.ForeignKey(blank=True, help_text='Most requirements apply identically to all dance roles.  If this requirement does not, then specify the role to which it applies here.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DanceRole', verbose_name='Applies only to role (optional)'),
        ),
        migrations.AlterField(
            model_name='requirementitem',
            name='requiredClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ClassDescription', verbose_name='Required class'),
        ),
        migrations.AlterField(
            model_name='requirementitem',
            name='requiredLevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DanceTypeLevel', verbose_name='Required Dance type/level'),
        ),
    ]
