# Generated by Django 2.2.6 on 2019-10-29 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0004_auto_20191025_1826'),
        ('prerequisites', '0004_auto_20190322_2346'),
    ]

    operations = [
    ]
