# Generated by Django 3.1.6 on 2021-02-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0006_auto_20200105_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementitem',
            name='concurrentRule',
            field=models.CharField(choices=[('P', 'Must have previously taken'), ('1', 'May register/begin with one class remaining'), ('2', 'May register/begin with two classes remaining'), ('A', 'Concurrent registration allowed'), ('R', 'Concurrent registration required')], default='P', max_length=1, verbose_name='Concurrency Rule'),
        ),
    ]
