# Generated by Django 5.2.3 on 2026-03-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0007_auto_20210212_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='enforcementMethod',
            field=models.CharField(choices=[('N', 'Enforcement disabled'), ('W', 'Allow registration with warning'), ('E', 'Raise error and do not allow registration'), ('A', 'Require acknowledgement checkbox')], default='W', max_length=1, verbose_name='Enforcement method'),
        ),
    ]
