# Generated by Django 2.2.6 on 2020-01-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorregistereventpluginchoice',
            name='optionType',
            field=models.CharField(choices=[('G', 'Standard registration'), ('D', 'Register as a drop-in'), ('S', 'Register with student designation')], default='G', max_length=1, verbose_name='Option type'),
        ),
        migrations.AlterField(
            model_name='doorregistereventpluginchoice',
            name='voucherId',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Optional voucher code to be added simultaneously'),
        ),
    ]
