# Generated by Django 2.2.6 on 2020-01-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200106_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorregisterpaymentmethod',
            name='allowAutoSubmit',
            field=models.BooleanField(default=False, help_text='If the payatdoor app is enabled, this setting can be used to permit automatic recording of non-electronic door payments to speed the registration process. For auto-submission to work, the name of this payment method must match the name of a payment method in the setting ATTHEDOOR_PAYMENTMETHOD_CHOICES for the payatdoor app. Valid defaults are Cash and Check.', verbose_name='Auto-submission'),
        ),
        migrations.AlterField(
            model_name='doorregisterpaymentmethod',
            name='requireFullRegistration',
            field=models.BooleanField(default=False, help_text='If checked, then whenever this payment method is used, the student information form will be required. The full registration process may also be required by a particular register plugin or registration choice.', verbose_name='Is full registration (name and email) always required for this method?'),
        ),
    ]
