# Generated by Django 2.2.6 on 2020-01-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200106_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorregistereventpluginmodel',
            name='occursWithinDays',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='If set, then the register will only include events that have an occurrence within this many days in the future of the register date(usually) the current date. The default of 0 limits to only events that occur on the register date. Leave blank for no restriction.', null=True, verbose_name='Event occurs within __ days'),
        ),
    ]
