# Generated by Django 2.2.6 on 2020-01-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200107_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorregistereventpluginchoice',
            name='registrationOpenDisplay',
            field=models.CharField(choices=[('O', 'Open for registration only'), ('C', 'Closed for registration only'), ('B', 'Both open and closed events')], default='B', max_length=1, verbose_name='Display if open/closed for registration only'),
        ),
    ]
