# Generated by Django 3.1.6 on 2021-02-20 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_invoiceitem_data'),
        ('cms', '0022_auto_20180620_1551'),
        ('merch', '0005_auto_20210220_0056'),
        ('register', '0007_auto_20210217_1457'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoorRegister',
            new_name='Register',
        ),
        migrations.RenameModel(
            old_name='DoorRegisterEventPluginChoice',
            new_name='RegisterEventPluginChoice',
        ),
        migrations.RenameModel(
            old_name='DoorRegisterPaymentMethod',
            new_name='RegisterPaymentMethod',
        ),
        migrations.RenameModel(
            old_name='DoorRegisterEventPluginModel',
            new_name='RegisterEventPluginModel'
        ),
        migrations.RenameModel(
            old_name='DoorRegisterGuestSearchPluginModel',
            new_name='RegisterGuestSearchPluginModel'
        ),
    ]
